version: "2.0"
services:
  backend:
    build: .
    ports:
      - "8732:8080"
    links:
      - db
    environment:
      POSTGRES_URL: "postgres://admin:password@localhost:8733/gushkinlocal?sslmode=disable"
  db:
    image: postgres
    ports:
      - "8733:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gushkinlocal
